apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
  namespace: roey-training
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: roia5/tasks:latest
        ports:
        - containerPort: 4000