apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo
type: Opaque
data:
  token: Z2hwX1docW9xdXJNM2tzaGdZVnI0SzByUk8xeGFLa3VHVTNtbmt2eg==
  user: Um9pYTUK
  email: cm9leWFzaDVAZ21haWwuY29tCg==