
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operate-workflow-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
