apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: roey-training
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: roia5/client:latest
        ports:
        - containerPort: 3000