apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-deployment
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: roia5/todo-ui52925
        ports:
        - containerPort: 3000