apiVersion: v1
kind: Service
metadata:
  name: todo-ui-service
spec:
  type: LoadBalancer
  selector:
    app: todo-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # port 80 for nginx